### ISSUE TITLE
Error: Cannot find module '_process' when require timesync client in nodejs

### ISSUE THREAD

**Issue by minusplusminus** [enmasseio/timesync#6]
Hi,

I'm trying to use timesync client in nodejs, but I get an error back when requiring the js file: 

`var timesync = require('./node_modules/timesync/dist/timesync.js');`

this is the error
`Error: Cannot find module '_process'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at s (/Users/martijnmellema/Documents/Development/Projecten/groenewijkstroom/wijk-client/node_modules/timesync/dist/timesync.js:1:502)
    at /Users/martijnmellema/Documents/Development/Projecten/groenewijkstroom/wijk-client/node_modules/timesync/dist/timesync.js:1:647
    at Object.14._process (/Users/martijnmellema/Documents/Development/Projecten/groenewijkstroom/wijk-client/node_modules/timesync/dist/timesync.js:1061:14)
    at s (/Users/martijnmellema/Documents/Development/Projecten/groenewijkstroom/wijk-client/node_modules/timesync/dist/timesync.js:1:596)
    at /Users/martijnmellema/Documents/Development/Projecten/groenewijkstroom/wijk-client/node_modules/timesync/dist/timesync.js:1:647
    at Object.10.asap (/Users/martijnmellema/Documents/Development/Projecten/groenewijkstroom/wijk-client/node_modules/timesync/dist/timesync.js:651:12)`

Tried adding the shim files, but still no result:
```

require('es6-shim');
require('es5-shim');
```

using nodejs 4.4.5

**Comment by minusplusminus** [comment]
thanks!

**Comment by josdejong** [comment]
Thank you :) 

Should be fixed in v0.2.1
